#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 14 21:40:51 2018

@author: wenyijones
"""


x1="EBADAEEABBBCEDE"
x2="ACBAAABDCAEADCEEBBDADDCEBCADCAEBBCDCAEDAC"

x3="BBAA"
x4="ABABB"
